# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "BLUETOWN"
description: > # this means to ignore newlines until "email:"
   17th street

email: bluetown17@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "http://www.viewfrom5ft2.com/wp-content/uploads/2010/07/City-Street.jpg"
name: 'bluetown'
author: 'bluetown'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://Mngment.github.io"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/BlueTown17
    desc: Follow me on twitter
    share_url: http://twitter.com/BlueTown17
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mngment
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
